import type { GameDefinition } from '../types/game';

// STARTUP SPRINT CONTENT: this entire definition is replaceable. The reusable
// engine imports only the GameDefinition interface and never assumes this topic.
export const startupSprint: GameDefinition = {
  id: 'startup-sprint',
  title: 'Startup Sprint',
  subtitle: 'Five decisions. Limited resources. What will you learn before you build?',
  description: 'A story-driven introduction to customer discovery, evidence, and testing ideas under uncertainty.',
  learningObjective: 'Distinguish an exciting idea from a demonstrated customer problem, then choose an evidence-based next step.',
  targetLearner: 'High school students new to entrepreneurship',
  setting: 'The Launch Lab, five days before a school innovation showcase',
  playerRole: 'An aspiring entrepreneur leading a small team with an early peer-tutoring idea',
  openingStory: 'You and Jordan have an idea: MatchPoint, a mobile service that helps students find and coordinate peer tutoring. The showcase is close. You have $100, five blocks of focused time, and one important question: what should your team do next?',
  instructions: 'Read each scene, consult the characters, and choose a course of action. Choices change resources and evidence. There is no single perfect route—look for what your decisions actually teach you.',
  estimatedPlayTime: '5–8 minutes',
  status: 'published',
  chapters: [
    { id: 'discover', title: 'Discover', summary: 'Move from idea excitement to a specific problem.', learningFocus: 'Problems, customers, and assumptions', completionRequirements: 'Complete scenes 1–3', sortOrder: 1 },
    { id: 'test', title: 'Test & Decide', summary: 'Design a useful experiment and make an evidence-based next step.', learningFocus: 'Experiments and decisions under uncertainty', completionRequirements: 'Complete scenes 4–5', sortOrder: 2 },
  ],
  characters: [
    { id: 'jordan', name: 'Jordan', role: 'Enthusiastic co-founder', description: 'A creative teammate who turns ideas into action.', personality: 'Optimistic, energetic, inventive, and attached to the original concept.', goals: 'Build momentum and make MatchPoint feel real.', relationship: 'Your co-founder and ally', initials: 'JO', color: '#f0a45d', openingDialogue: 'We could have a clickable prototype by tomorrow.', aiEnabled: false, educationalPurpose: 'Represents the legitimate pull of speed, confidence, and visible progress.', knowledgeBoundaries: 'Knows only what the team has observed.', avoidTopics: 'Personal information', maxAiInteractions: 0, sortOrder: 1 },
    { id: 'maya', name: 'Maya', role: 'Potential customer', description: 'A busy student who sometimes helps classmates study.', personality: 'Candid, practical, and unimpressed by leading questions.', goals: 'Spend less time coordinating study help.', relationship: 'A potential customer you are interviewing', initials: 'MA', color: '#5fb6aa', openingDialogue: 'Tutoring? Sometimes. It depends what you mean.', aiEnabled: false, educationalPurpose: 'Shows the difference between opinions and accounts of real behavior.', knowledgeBoundaries: 'Speaks only from her own experience.', avoidTopics: 'Personal information', maxAiInteractions: 0, sortOrder: 2 },
    { id: 'rivera', name: 'Professor Rivera', role: 'AI entrepreneurship mentor', description: 'A mentor who asks the hard question before offering a hint.', personality: 'Warm, precise, patient, and evidence-minded.', goals: 'Help the player reason without making the decision for them.', relationship: 'Your mentor at the Launch Lab', initials: 'PR', color: '#7c75d6', openingDialogue: 'Before you build, what would need to be true for this idea to matter?', aiEnabled: true, educationalPurpose: 'Scaffolds customer discovery and experiment design.', knowledgeBoundaries: 'Uses only the game definition, current state, and supplied recent context.', avoidTopics: 'Personal, confidential, identifying, medical, legal, or financial information', maxAiInteractions: 4, sortOrder: 3 },
    { id: 'alex', name: 'Alex', role: 'Skeptical advisor', description: 'A sharp reviewer who separates a compelling story from supporting evidence.', personality: 'Direct, fair, and constructively skeptical.', goals: 'Stress-test the team’s interpretation before the showcase.', relationship: 'A volunteer innovation advisor', initials: 'AL', color: '#e06d67', openingDialogue: 'Who has this problem badly enough to change what they do?', aiEnabled: false, educationalPurpose: 'Creates productive tension and surfaces remaining uncertainty.', knowledgeBoundaries: 'Evaluates only collected evidence.', avoidTopics: 'Personal information', maxAiInteractions: 0, sortOrder: 4 },
  ],
  variables: [
    { id: 'cash', name: 'cash', label: 'Cash', startingValue: 100, min: 0, max: 100, icon: '$', explanation: 'Money left for learning and building.', sortOrder: 1 },
    { id: 'time', name: 'time', label: 'Time', startingValue: 100, min: 0, max: 100, icon: '◷', explanation: 'Focused time left before the decision.', sortOrder: 2 },
    { id: 'evidence', name: 'evidence', label: 'Customer Evidence', startingValue: 5, min: 0, max: 100, icon: '◇', explanation: 'Quality of evidence about behavior and demand.', sortOrder: 3 },
    { id: 'confidence', name: 'confidence', label: 'Team Confidence', startingValue: 55, min: 0, max: 100, icon: '↗', explanation: 'How strongly the team believes—independent of evidence.', sortOrder: 4 },
  ],
  inventory: [
    { id: 'interview-notes', name: 'Customer interview notes', description: 'Specific stories about the last time students sought help.', type: 'evidence', icon: '▤', sortOrder: 1 },
    { id: 'pattern-summary', name: 'Problem pattern summary', description: 'A comparison of recurring behaviors and workarounds.', type: 'evidence', icon: '⌁', sortOrder: 2 },
    { id: 'pilot-results', name: 'Pilot-session results', description: 'Observed commitments and outcomes from a manual test.', type: 'evidence', icon: '✓', sortOrder: 3 },
    { id: 'landing-results', name: 'Landing-page results', description: 'Interest data from a focused call to action.', type: 'evidence', icon: '▱', sortOrder: 4 },
  ],
  scenes: [
    {
      id: 'big-idea', chapterId: 'discover', title: 'The Big Idea', location: 'Launch Lab · Monday', sortOrder: 1,
      narrative: 'Jordan spins a laptop toward you. A polished MatchPoint logo fills the screen. The idea feels tangible—but the team has not yet agreed on whose problem it solves most urgently.',
      objective: 'Choose the first use of your limited resources.', learningFocus: 'An idea is a proposed solution; a problem is a specific struggle experienced by a specific person.', characterIds: ['jordan'],
      dialogue: [
        { id: 'd1', characterId: 'jordan', text: 'People always say finding a tutor is hard. If we move fast, we can show everyone the whole experience.', sortOrder: 1 },
        { id: 'd2', characterId: 'jordan', text: 'Or we could talk to students first. I just don’t want us to lose momentum.', sortOrder: 2 },
      ],
      decision: { id: 'first-move', prompt: 'What should the team do first?', context: 'The showcase is in five days. Activity can create momentum, but only some activity reduces uncertainty.', choices: [
        { id: 'build-now', label: 'Build the full prototype', description: 'Turn the idea into a convincing product demo.', consequence: 'The prototype looks real, but the team spends heavily before defining the customer problem.', feedback: 'You tested whether the team could build—not whether students have an important, unsolved problem. The visible progress raises confidence while key demand assumptions remain.', variableEffects: [{ variableId: 'cash', amount: -35 }, { variableId: 'time', amount: -30 }, { variableId: 'evidence', amount: 3 }, { variableId: 'confidence', amount: 18 }], itemEffects: [], sortOrder: 1 },
        { id: 'interview-first', label: 'Interview potential customers', description: 'Ask students about recent tutoring experiences.', consequence: 'You reserve time with students and begin defining the problem from real experiences.', feedback: 'Customer conversations can reveal frequency, stakes, and workarounds. Their quality will depend on whether you ask about behavior rather than invite compliments.', variableEffects: [{ variableId: 'cash', amount: -5 }, { variableId: 'time', amount: -15 }, { variableId: 'evidence', amount: 10 }, { variableId: 'confidence', amount: -2 }], itemEffects: [], sortOrder: 2 },
        { id: 'research-alternatives', label: 'Map existing alternatives', description: 'Study how students already find help.', consequence: 'You discover group chats, teacher office hours, and informal friend networks.', feedback: 'Alternatives reveal what customers already “hire” to solve the problem. Desk research gives context, though it cannot replace observing real behavior.', variableEffects: [{ variableId: 'cash', amount: -2 }, { variableId: 'time', amount: -12 }, { variableId: 'evidence', amount: 8 }, { variableId: 'confidence', amount: -4 }], itemEffects: [{ itemId: 'pattern-summary', action: 'award' }], sortOrder: 3 },
        { id: 'brand-first', label: 'Launch the brand', description: 'Create social accounts and collect likes.', consequence: 'The posts attract encouragement from friends, and the team feels energized.', feedback: 'Attention can test messaging, but likes from a broad audience are weak evidence of a painful problem or future behavior.', variableEffects: [{ variableId: 'cash', amount: -12 }, { variableId: 'time', amount: -18 }, { variableId: 'evidence', amount: 2 }, { variableId: 'confidence', amount: 20 }], itemEffects: [], sortOrder: 4 },
      ] }, nextSceneId: 'customer-discovery'
    },
    {
      id: 'customer-discovery', chapterId: 'discover', title: 'Customer Discovery', location: 'School Commons · Tuesday', sortOrder: 2,
      narrative: 'Maya agrees to talk. Jordan has drafted a list of questions, starting with “Would you use MatchPoint?” Professor Rivera is available to help you improve the interview before it begins.',
      objective: 'Choose questions that uncover behavior instead of approval.', learningFocus: 'Specific stories about past behavior are usually stronger evidence than predictions or politeness.', characterIds: ['maya', 'rivera'], aiCharacterId: 'rivera', aiPrompt: 'Ask Professor Rivera how to improve a customer interview or distinguish strong evidence from polite encouragement.',
      dialogue: [
        { id: 'd3', characterId: 'maya', text: 'I can tell you whether the idea sounds nice, but I’m not sure that tells you what I’d actually do.', sortOrder: 1 },
        { id: 'd4', characterId: 'rivera', text: 'A useful interview reconstructs a real event. What could you ask that does not require Maya to predict the future?', sortOrder: 2 },
      ],
      decision: { id: 'interview-method', prompt: 'How will you conduct the interview?', context: 'Maya has ten minutes. Your wording will shape the kind of evidence you collect.', choices: [
        { id: 'leading-pitch', label: 'Pitch, then ask if she likes it', description: 'Explain every feature and ask for a reaction.', consequence: 'Maya says it sounds helpful. You leave with enthusiasm, but few details about her behavior.', feedback: 'A positive reaction is an opinion shaped by your pitch. You did not learn how often the problem occurs, what Maya currently does, or whether she would change.', variableEffects: [{ variableId: 'time', amount: -10 }, { variableId: 'evidence', amount: 4 }, { variableId: 'confidence', amount: 15 }], itemEffects: [], sortOrder: 1 },
        { id: 'past-behavior', label: 'Reconstruct the last incident', description: 'Ask what happened, what she tried, and what it cost.', consequence: 'Maya describes missing a review session, searching three group chats, then asking a friend. The hassle was real but occasional.', feedback: 'You gained behavioral detail: context, workaround, frequency, and cost. You also learned the problem may be narrower than first assumed.', variableEffects: [{ variableId: 'time', amount: -15 }, { variableId: 'evidence', amount: 22 }, { variableId: 'confidence', amount: -5 }], itemEffects: [{ itemId: 'interview-notes', action: 'award' }], sortOrder: 2 },
        { id: 'future-price', label: 'Ask what she would pay', description: 'Describe the app and request a hypothetical price.', consequence: 'Maya guesses “maybe a few dollars,” then admits she normally asks friends for free.', feedback: 'Hypothetical willingness to pay is weak without a real commitment. The mention of free alternatives is useful evidence that deserves follow-up.', variableEffects: [{ variableId: 'time', amount: -10 }, { variableId: 'evidence', amount: 7 }, { variableId: 'confidence', amount: 6 }], itemEffects: [], sortOrder: 3 },
        { id: 'frequency-scan', label: 'Ask about frequency and alternatives', description: 'Compare recent experiences across different classes.', consequence: 'Maya reveals that advanced math students seek help repeatedly, while most others use existing school resources.', feedback: 'Frequency and segmentation help locate where the problem is strongest. You still need to observe whether that segment will take meaningful action.', variableEffects: [{ variableId: 'time', amount: -14 }, { variableId: 'evidence', amount: 18 }, { variableId: 'confidence', amount: 1 }], itemEffects: [{ itemId: 'interview-notes', action: 'award' }], sortOrder: 4 },
      ] }, nextSceneId: 'conflicting-evidence'
    },
    {
      id: 'conflicting-evidence', chapterId: 'discover', title: 'Conflicting Evidence', location: 'Library Steps · Wednesday', sortOrder: 3,
      narrative: 'Seven students called MatchPoint “cool.” Only two described searching repeatedly for help, and both were taking advanced math. Jordan sees broad enthusiasm. You see a pattern—but perhaps not the one you expected.',
      objective: 'Interpret mixed evidence without forcing it to support the original idea.', learningFocus: 'Opinions, intentions, and behavior are different levels of evidence.', characterIds: ['jordan', 'maya'],
      dialogue: [
        { id: 'd5', characterId: 'jordan', text: 'Seven positive reactions! That’s enough to show people want it, right?', sortOrder: 1 },
        { id: 'd6', characterId: 'maya', text: 'The advanced math group actually schedules help every week. Most of my friends just said the app sounded nice.', sortOrder: 2 },
      ],
      decision: { id: 'interpret-evidence', prompt: 'What conclusion will guide the next test?', context: 'Mixed findings can justify learning more, narrowing focus, or stopping—but not pretending uncertainty has disappeared.', choices: [
        { id: 'comments-proof', label: 'Count positive comments as demand', description: 'Keep the broad audience and move ahead.', consequence: 'The team rallies around the seven compliments and stops investigating differences between students.', feedback: 'You selected confirming evidence and treated stated interest like behavior. The main assumptions—frequency, urgency, and commitment—remain untested.', variableEffects: [{ variableId: 'time', amount: -8 }, { variableId: 'evidence', amount: 2 }, { variableId: 'confidence', amount: 17 }], itemEffects: [], sortOrder: 1 },
        { id: 'targeted-interviews', label: 'Interview the recurring users', description: 'Study students who seek help every week.', consequence: 'You focus on a smaller group with repeated behavior and document its existing routines.', feedback: 'Targeting a behaviorally defined segment makes evidence more relevant. A narrower market is not automatically a worse one; it creates a testable claim.', variableEffects: [{ variableId: 'cash', amount: -4 }, { variableId: 'time', amount: -15 }, { variableId: 'evidence', amount: 19 }, { variableId: 'confidence', amount: 2 }], itemEffects: [{ itemId: 'pattern-summary', action: 'award' }], sortOrder: 2 },
        { id: 'narrow-segment', label: 'Narrow to advanced math', description: 'Reframe the concept around a frequent need.', consequence: 'The original broad app becomes a focused coordination experiment for advanced math courses.', feedback: 'Segmentation is a hypothesis, not proof. It improves focus and makes the next experiment more informative while changing the original vision.', variableEffects: [{ variableId: 'time', amount: -10 }, { variableId: 'evidence', amount: 14 }, { variableId: 'confidence', amount: -7 }], itemEffects: [{ itemId: 'pattern-summary', action: 'award' }], sortOrder: 3 },
        { id: 'stop-immediately', label: 'Stop immediately', description: 'Treat mixed evidence as a complete rejection.', consequence: 'You preserve resources but do not investigate the recurring advanced-math pattern.', feedback: 'Stopping can be disciplined, but this conclusion may be premature: mixed evidence identified a smaller promising segment that remains untested.', variableEffects: [{ variableId: 'confidence', amount: -30 }, { variableId: 'evidence', amount: 3 }], itemEffects: [], nextSceneId: 'final-decision', sortOrder: 4 },
      ] }, nextSceneId: 'what-to-build'
    },
    {
      id: 'what-to-build', chapterId: 'test', title: 'What Should We Build?', location: 'Launch Lab · Thursday', sortOrder: 4,
      narrative: 'The clock is moving. A complete platform would look impressive, but the uncertain assumption is whether students will commit to a scheduled peer session. Professor Rivera asks you to define what the next test must teach.',
      objective: 'Design the cheapest credible test of the riskiest assumption.', learningFocus: 'A minimum useful experiment minimizes cost while producing decision-relevant evidence.', characterIds: ['jordan', 'rivera'], aiCharacterId: 'rivera', aiPrompt: 'Ask Professor Rivera to help identify the riskiest assumption or compare a prototype, landing page, and manual test.',
      dialogue: [
        { id: 'd7', characterId: 'jordan', text: 'If we build the matching algorithm, people will understand how powerful this could be.', sortOrder: 1 },
        { id: 'd8', characterId: 'rivera', text: 'What do you need to learn that a polished interface cannot tell you?', sortOrder: 2 },
      ],
      decision: { id: 'experiment', prompt: 'Which experiment will you run?', context: 'Consider cost, speed, realism, and whether the result changes your next decision.', choices: [
        { id: 'complete-product', label: 'Build the complete product', description: 'Automate matching, messaging, profiles, and scheduling.', consequence: 'The team produces an impressive demo but has almost no time to observe genuine use.', feedback: 'Product completion reduced technical uncertainty. It did little to test whether the problem is frequent or whether customers will commit.', variableEffects: [{ variableId: 'cash', amount: -45 }, { variableId: 'time', amount: -40 }, { variableId: 'evidence', amount: 5 }, { variableId: 'confidence', amount: 16 }], itemEffects: [], sortOrder: 1 },
        { id: 'limited-prototype', label: 'Build a focused prototype', description: 'Test only search and scheduling with a small group.', consequence: 'Students can react to the workflow, though most interactions are still hypothetical.', feedback: 'A limited prototype can reveal usability and comprehension. It is less reliable for proving repeated demand unless paired with real commitments.', variableEffects: [{ variableId: 'cash', amount: -20 }, { variableId: 'time', amount: -25 }, { variableId: 'evidence', amount: 13 }, { variableId: 'confidence', amount: 8 }], itemEffects: [{ itemId: 'landing-results', action: 'award' }], sortOrder: 2 },
        { id: 'concierge-test', label: 'Run a manual concierge pilot', description: 'Personally match six students and require scheduled attendance.', consequence: 'Four students commit and three attend. Coordination is messy, but you observe real behavior and a useful failure point.', feedback: 'The manual test sacrifices scale to gain behavioral evidence quickly. Attendance is stronger than compliments, while the drop-off reveals remaining friction.', variableEffects: [{ variableId: 'cash', amount: -8 }, { variableId: 'time', amount: -22 }, { variableId: 'evidence', amount: 28 }, { variableId: 'confidence', amount: 5 }], itemEffects: [{ itemId: 'pilot-results', action: 'award' }], sortOrder: 3 },
        { id: 'landing-test', label: 'Test a focused sign-up page', description: 'Ask one segment to reserve a real session.', consequence: 'The page is inexpensive and reaches more students; sign-ups provide a commitment signal, but not proof of attendance.', feedback: 'A focused call to action is stronger than general likes and cheaper than a full build. You still need evidence that sign-ups turn into use.', variableEffects: [{ variableId: 'cash', amount: -5 }, { variableId: 'time', amount: -12 }, { variableId: 'evidence', amount: 18 }, { variableId: 'confidence', amount: 4 }], itemEffects: [{ itemId: 'landing-results', action: 'award' }], sortOrder: 4 },
      ] }, nextSceneId: 'final-decision'
    },
    {
      id: 'final-decision', chapterId: 'test', title: 'Proceed, Pivot, or Pause', location: 'Innovation Showcase · Friday', sortOrder: 5,
      narrative: 'Alex reviews the board: resources spent, claims tested, behavior observed, and assumptions still open. The goal is not to defend the original idea. It is to choose a next step that fits the evidence.',
      objective: 'Make an evidence-based decision and name what remains uncertain.', learningFocus: 'Proceeding, pivoting, and stopping can each be disciplined when the evidence supports them.', characterIds: ['alex', 'jordan'],
      dialogue: [
        { id: 'd9', characterId: 'alex', text: 'Tell me what people did—not what they said. Then tell me what you still do not know.', sortOrder: 1 },
        { id: 'd10', characterId: 'jordan', text: 'Whatever we decide, I want it to be because we learned something real.', sortOrder: 2 },
      ],
      decision: { id: 'venture-decision', prompt: 'What is the team’s next step?', context: 'Your ending will consider this decision, your resources, evidence quality, and collected artifacts.', choices: [
        { id: 'proceed-original', label: 'Launch the original broad concept', description: 'Keep the solution and audience unchanged.', consequence: 'The team commits to the original vision and treats the showcase as a launch.', feedback: 'Proceeding preserves momentum, but its strength depends on whether your evidence supports this exact customer, problem, and solution—not merely tutoring in general.', variableEffects: [{ variableId: 'cash', amount: -10 }, { variableId: 'time', amount: -8 }, { variableId: 'confidence', amount: 12 }], itemEffects: [], sortOrder: 1 },
        { id: 'proceed-focused', label: 'Run a focused next experiment', description: 'Serve the recurring-use segment and test retention.', consequence: 'The team defines a limited next step with a measurable learning goal.', feedback: 'A focused next experiment connects action to remaining uncertainty. It is strongest when prior evidence identifies a specific segment and behavior.', variableEffects: [{ variableId: 'cash', amount: -4 }, { variableId: 'time', amount: -5 }, { variableId: 'evidence', amount: 5 }, { variableId: 'confidence', amount: 3 }], itemEffects: [], sortOrder: 2 },
        { id: 'pivot-solution', label: 'Pivot the solution', description: 'Explore lightweight study-session coordination instead of an app.', consequence: 'The original product changes, while the observed problem and customer behavior guide a simpler approach.', feedback: 'A pivot keeps a supported insight while changing an unsupported assumption. It is not random change; it should trace back to evidence.', variableEffects: [{ variableId: 'cash', amount: 0 }, { variableId: 'evidence', amount: 7 }, { variableId: 'confidence', amount: -4 }], itemEffects: [], sortOrder: 3 },
        { id: 'disciplined-stop', label: 'Pause and preserve resources', description: 'Document the learning and stop this opportunity for now.', consequence: 'The team closes the experiment, preserves what remains, and records what would justify returning.', feedback: 'Stopping is productive when evidence does not justify further investment. The value lies in a clear rationale, preserved resources, and transferable learning.', variableEffects: [{ variableId: 'confidence', amount: -12 }], itemEffects: [], sortOrder: 4 },
      ] }
    },
  ],
  endings: [
    { id: 'productive-pivot', title: 'Productive Pivot', narrative: 'MatchPoint changes shape. Your team follows the strongest observed behavior toward a smaller, simpler coordination service.', explanation: 'You treated the original solution as a hypothesis and preserved the customer insight that earned support.', learningDebrief: 'A pivot is disciplined when it retains evidence and changes an assumption—not when it simply chases novelty.', principles: ['Evidence can improve an idea by changing it.', 'Specific customers make experiments clearer.', 'A smaller test can produce a stronger decision.'], reflectionQuestion: 'Which assumption did you change, and what evidence justified that change?', replaySuggestion: 'Replay and compare the concierge pilot with a full-product build.', conditions: [{ choiceId: 'pivot-solution' }], priority: 100, tone: 'pivot', sortOrder: 1 },
    { id: 'disciplined-stop-ending', title: 'Disciplined Stop', narrative: 'You pause the venture without calling the sprint a failure. The team leaves with resources, documented learning, and a clear standard for revisiting the opportunity.', explanation: 'You decided the current evidence did not justify continued investment.', learningDebrief: 'Entrepreneurship includes deciding what not to build. A well-reasoned stop converts uncertainty into preserved options.', principles: ['Stopping can be an evidence-based outcome.', 'Sunk effort should not dictate the next investment.', 'Documented learning remains valuable.'], reflectionQuestion: 'What new evidence would make this opportunity worth reopening?', replaySuggestion: 'Replay using targeted interviews before choosing whether to stop.', conditions: [{ choiceId: 'disciplined-stop' }], priority: 95, tone: 'stop', sortOrder: 2 },
    { id: 'premature-build', title: 'Premature Build', narrative: 'The demo earns attention, but the central customer questions remain unanswered and your resources are nearly gone.', explanation: 'The team invested in product certainty before establishing strong problem or demand evidence.', learningDebrief: 'Building produces an artifact. It does not automatically produce customer evidence. The cost matters because it reduces the experiments still available.', principles: ['Progress and learning are not identical.', 'Test demand before scaling a solution.', 'Resources spent are experiments forgone.'], reflectionQuestion: 'What is the cheapest test you could have run before building?', replaySuggestion: 'Replay and choose questions about past behavior, then run a manual pilot.', conditions: [{ variableId: 'cash', operator: 'lte', value: 25 }, { variableId: 'evidence', operator: 'lt', value: 55 }], priority: 85, tone: 'mixed', sortOrder: 3 },
    { id: 'popular-unproven', title: 'Popular but Unproven', narrative: 'People like the story of MatchPoint, and your team feels energized. The evidence board, however, contains more compliments than commitments.', explanation: 'Confidence rose faster than evidence because opinions were treated as demand.', learningDebrief: 'Enthusiasm is useful for motivation and messaging, but behavior and commitment are stronger signals for investment decisions.', principles: ['Confidence and evidence are separate variables.', 'Stated interest is not the same as behavior.', 'Confirmation bias can hide uncertainty.'], reflectionQuestion: 'Which positive signal did you overvalue, and how could you test it?', replaySuggestion: 'Replay and ask about the last real incident rather than future interest.', conditions: [{ variableId: 'confidence', operator: 'gte', value: 75 }, { variableId: 'evidence', operator: 'lt', value: 55 }], priority: 80, tone: 'mixed', sortOrder: 4 },
    { id: 'evidence-next-step', title: 'Evidence-Based Next Step', narrative: 'Your team leaves the showcase with a specific customer, a supported problem pattern, and a focused next experiment—not a promise that success is guaranteed.', explanation: 'You matched the size of the next investment to the quality of the evidence collected.', learningDebrief: 'Strong entrepreneurial progress is a chain of increasingly credible tests. Uncertainty remains, but the next action is designed to reduce the most important part of it.', principles: ['Past behavior is stronger than polite prediction.', 'Test the riskiest assumption with the smallest credible experiment.', 'A focused next step can be better than a broad launch.'], reflectionQuestion: 'What remains most uncertain, and what observable result would reduce that uncertainty?', replaySuggestion: 'Replay with a different test and compare what each result can—and cannot—prove.', conditions: [{ variableId: 'evidence', operator: 'gte', value: 55 }, { choiceId: 'proceed-focused' }], priority: 75, tone: 'strong', sortOrder: 5 },
    { id: 'mixed-next-step', title: 'A Hypothesis in Motion', narrative: 'You finish with mixed signals and a decision to keep learning. The opportunity is neither validated nor disproven.', explanation: 'Your evidence supports continued curiosity but not certainty.', learningDebrief: 'Early decisions rarely eliminate uncertainty. Good process makes the next uncertainty explicit and limits the cost of being wrong.', principles: ['Name uncertainty before acting.', 'Match investment to evidence.', 'Mixed results are information.'], reflectionQuestion: 'What result would cause you to change direction next?', replaySuggestion: 'Replay and compare how customer questions change the final evidence.', conditions: [], priority: 1, tone: 'mixed', sortOrder: 6 },
  ],
};

export default startupSprint;
